/*
 *
 *  constants
 *
 */

export const SET_CURRENT_PRODUCT = 'app/LoginPage/SET_CURRENT_PRODUCT'
export const GET_MOBILE_NUMBERS = 'app/LoginPage/GET_MOBILE_NUMBERS'
export const UPDATE_MOBILE_NUMBERS = 'app/LoginPage/UPDATE_MOBILE_NUMBERS'
export const SET_MOBILE_NUMBERS = 'app/LoginPage/SET_MOBILE_NUMBERS'

// This will set our /success and error handler to default
export const SET_PRODUCT_HANDLER_DEFAULT = 'app/LoginPage/SET_PRODUCT_HANDLER_DEFAULT'

// Terms And Conditions
export const GET_MARKDOWN = 'app/LoginPage/GET_MARKDOWN'
export const SET_MARKDOWN = 'app/LoginPage/SET_MARKDOWN'

export const SET_VERIFICATION_CODE = 'app/LoginPage/SET_VERIFICATION_CODE'

export const REQUEST_MOBILE_REGISTRATION = 'app/LoginPage/REQUEST_MOBILE_REGISTRATION'
export const SUCCESS_MOBILE_REGISTRATION = 'app/LoginPage/SUCCESS_MOBILE_REGISTRATION'
export const ERROR_MOBILE_REGISTRATION = 'app/LoginPage/ERROR_MOBILE_REGISTRATION'

export const REQUEST_VERIFICATION_CODE = 'app/LoginPage/REQUEST_VERIFICATION_CODE'
export const SUCCESS_VERIFICATION_CODE = 'app/LoginPage/SUCCESS_VERIFICATION_CODE'
export const ERROR_VERIFICATION_CODE = 'app/LoginPage/ERROR_VERIFICATION_CODE'

export const RESET_SUBMISSION = 'app/LoginPage/RESET_SUBMISSION'

export const SET_TOGGLE = 'app/LoginPage/SET_TOGGLE'

export const REQUEST_RECAPTCHA_VALIDATION = 'app/LoginPage/REQUEST_RECAPTCHA_VALIDATION'
export const SUCCESS_RECAPTCHA_VALIDATION = 'app/LoginPage/SUCCESS_RECAPTCHA_VALIDATION'
export const ERROR_RECAPTCHA_VALIDATION = 'app/LoginPage/ERROR_RECAPTCHA_VALIDATION'
