/*
 *
 * HomePage constants
 *
 */

export const GET_FEATURED_PRODUCTS = 'app/HomePage/GET_FEATURED_PRODUCTS'
export const SET_FEATURED_PRODUCTS = 'app/HomePage/SET_FEATURED_PRODUCTS'

export const GET_FEATURED_CATEGORIES = 'app/HomePage/GET_FEATURED_CATEGORIES'
export const SET_FEATURED_CATEGORIES = 'app/HomePage/SET_FEATURED_CATEGORIES'

export const GET_FEATURED_BRANDS = 'app/HomePage/GET_FEATURED_BRANDS'
export const SET_FEATURED_BRANDS = 'app/HomePage/SET_FEATURED_BRANDS'
